edition = "2021"
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 20
struct_field_align_threshold = 20
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
